<a href="https://colab.research.google.com/github/Naga-SDonepudi/nlp_for_ml/blob/main/word_to_vector_representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Bag of Words (BoW)
* A technique is NLP used to convert words to vector rpresenation based on the frequency of words
* Before changing words to vectors, it counts how many times each word appears in a sentence.

In [106]:
import pandas as pd

In [107]:
matter = pd.read_csv('SMSSpamCollection.txt',
                    sep='\t',names=["label","text"])

In [108]:
matter

,label,text
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


### Data Preprocessing

In [109]:
import nltk
import re
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [110]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [111]:
port_stemmer = PorterStemmer()

In [112]:
corpus = []
for i in range(0, len(matter)):
  review=re.sub('[^a-zA-Z]',' ', matter['text'][i])
  review=review.lower()
  review=review.split()
  review=[port_stemmer.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

In [113]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

### Converting text to vectors using Bag of Words

In [114]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500, binary=True)

In [115]:
X= cv.fit_transform(corpus).toarray()

In [116]:
X.shape

(5572, 2500)

In [117]:
cv.vocabulary_

{'go': np.int64(865),
 'point': np.int64(1602),
 'crazi': np.int64(438),
 'avail': np.int64(143),
 'bugi': np.int64(269),
 'great': np.int64(899),
 'world': np.int64(2438),
 'la': np.int64(1156),
 'cine': np.int64(360),
 'got': np.int64(884),
 'wat': np.int64(2371),
 'ok': np.int64(1468),
 'lar': np.int64(1164),
 'joke': np.int64(1120),
 'wif': np.int64(2406),
 'oni': np.int64(1476),
 'free': np.int64(774),
 'entri': np.int64(602),
 'wkli': np.int64(2427),
 'comp': np.int64(394),
 'win': np.int64(2410),
 'fa': np.int64(666),
 'cup': np.int64(452),
 'final': np.int64(718),
 'tkt': np.int64(2219),
 'st': np.int64(2067),
 'may': np.int64(1302),
 'text': np.int64(2181),
 'receiv': np.int64(1763),
 'question': np.int64(1715),
 'std': np.int64(2078),
 'txt': np.int64(2276),
 'rate': np.int64(1740),
 'appli': np.int64(102),
 'dun': np.int64(564),
 'say': np.int64(1897),
 'earli': np.int64(568),
 'hor': np.int64(1006),
 'alreadi': np.int64(69),
 'nah': np.int64(1405),
 'think': np.int64(2195),

### N-Grams
* Used to capture contect and word relationships
* These are continuous sequences of N-words from a sentence

In [118]:
## Unigram
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100, binary=True, ngram_range=(1,1))
X = cv.fit_transform(corpus).toarray()
X.shape

(5572, 100)

In [119]:
cv.vocabulary_

{'go': np.int64(22),
 'great': np.int64(25),
 'got': np.int64(24),
 'wat': np.int64(90),
 'ok': np.int64(56),
 'free': np.int64(18),
 'win': np.int64(94),
 'text': np.int64(77),
 'txt': np.int64(85),
 'say': np.int64(67),
 'alreadi': np.int64(0),
 'think': np.int64(80),
 'hey': np.int64(28),
 'week': np.int64(92),
 'back': np.int64(3),
 'like': np.int64(38),
 'still': np.int64(73),
 'send': np.int64(69),
 'even': np.int64(15),
 'friend': np.int64(19),
 'prize': np.int64(62),
 'claim': np.int64(7),
 'call': np.int64(4),
 'mobil': np.int64(47),
 'co': np.int64(8),
 'home': np.int64(30),
 'want': np.int64(89),
 'today': np.int64(82),
 'cash': np.int64(6),
 'day': np.int64(12),
 'repli': np.int64(64),
 'www': np.int64(96),
 'right': np.int64(65),
 'thank': np.int64(78),
 'take': np.int64(75),
 'time': np.int64(81),
 'use': np.int64(87),
 'messag': np.int64(44),
 'oh': np.int64(55),
 'ye': np.int64(97),
 'make': np.int64(42),
 'way': np.int64(91),
 'feel': np.int64(16),
 'dont': np.int64(14

In [120]:
## Unigram & Bi-gram
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100, binary=True, ngram_range=(1,2))
X = cv.fit_transform(corpus).toarray()
X.shape

(5572, 100)

In [121]:
cv.vocabulary_

{'go': np.int64(21),
 'great': np.int64(24),
 'got': np.int64(23),
 'wat': np.int64(90),
 'ok': np.int64(56),
 'free': np.int64(17),
 'win': np.int64(94),
 'text': np.int64(77),
 'txt': np.int64(85),
 'say': np.int64(67),
 'alreadi': np.int64(0),
 'think': np.int64(80),
 'hey': np.int64(27),
 'week': np.int64(92),
 'back': np.int64(3),
 'like': np.int64(37),
 'still': np.int64(73),
 'send': np.int64(69),
 'even': np.int64(14),
 'friend': np.int64(18),
 'prize': np.int64(62),
 'claim': np.int64(7),
 'call': np.int64(4),
 'mobil': np.int64(47),
 'co': np.int64(8),
 'home': np.int64(29),
 'want': np.int64(89),
 'today': np.int64(82),
 'cash': np.int64(6),
 'day': np.int64(11),
 'repli': np.int64(64),
 'www': np.int64(96),
 'right': np.int64(65),
 'thank': np.int64(78),
 'take': np.int64(75),
 'time': np.int64(81),
 'use': np.int64(87),
 'messag': np.int64(44),
 'oh': np.int64(55),
 'ye': np.int64(97),
 'make': np.int64(42),
 'way': np.int64(91),
 'feel': np.int64(15),
 'dont': np.int64(13

In [122]:
## Unigram, bigram and trigram
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100, binary=True, ngram_range=(1,3))
X = cv.fit_transform(corpus).toarray()
X.shape

(5572, 100)

In [123]:
cv.vocabulary_

{'go': np.int64(22),
 'great': np.int64(25),
 'got': np.int64(24),
 'wat': np.int64(90),
 'ok': np.int64(57),
 'free': np.int64(18),
 'win': np.int64(94),
 'text': np.int64(78),
 'txt': np.int64(86),
 'say': np.int64(68),
 'alreadi': np.int64(0),
 'think': np.int64(81),
 'hey': np.int64(28),
 'week': np.int64(92),
 'back': np.int64(3),
 'like': np.int64(38),
 'still': np.int64(74),
 'send': np.int64(70),
 'even': np.int64(15),
 'friend': np.int64(19),
 'prize': np.int64(63),
 'claim': np.int64(7),
 'call': np.int64(4),
 'mobil': np.int64(48),
 'co': np.int64(8),
 'home': np.int64(30),
 'want': np.int64(89),
 'today': np.int64(83),
 'cash': np.int64(6),
 'day': np.int64(12),
 'repli': np.int64(65),
 'www': np.int64(96),
 'right': np.int64(66),
 'thank': np.int64(79),
 'take': np.int64(76),
 'time': np.int64(82),
 'messag': np.int64(45),
 'oh': np.int64(56),
 'ye': np.int64(97),
 'make': np.int64(43),
 'way': np.int64(91),
 'feel': np.int64(16),
 'dont': np.int64(14),
 'miss': np.int64(4

In [124]:
## Bigram and trigram
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100, binary=True, ngram_range=(2,3))
X = cv.fit_transform(corpus).toarray()
X.shape

(5572, 100)

In [125]:
cv.vocabulary_

{'free entri': np.int64(32),
 'claim call': np.int64(17),
 'call claim': np.int64(3),
 'free call': np.int64(31),
 'chanc win': np.int64(16),
 'txt word': np.int64(91),
 'let know': np.int64(53),
 'go home': np.int64(35),
 'pleas call': np.int64(69),
 'lt gt': np.int64(59),
 'want go': np.int64(97),
 'like lt': np.int64(54),
 'like lt gt': np.int64(55),
 'sorri call': np.int64(82),
 'call later': np.int64(11),
 'sorri call later': np.int64(83),
 'ur award': np.int64(92),
 'call custom': np.int64(4),
 'custom servic': np.int64(24),
 'cash prize': np.int64(15),
 'call custom servic': np.int64(5),
 'po box': np.int64(70),
 'tri contact': np.int64(88),
 'draw show': np.int64(28),
 'show prize': np.int64(80),
 'prize guarante': np.int64(74),
 'guarante call': np.int64(41),
 'valid hr': np.int64(95),
 'draw show prize': np.int64(29),
 'show prize guarante': np.int64(81),
 'prize guarante call': np.int64(75),
 'select receiv': np.int64(77),
 'privat account': np.int64(71),
 'account statement

In [126]:
## Bigram
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100, binary=True, ngram_range=(2,2))
X = cv.fit_transform(corpus).toarray()
X.shape

(5572, 100)

In [127]:
cv.vocabulary_

{'free entri': np.int64(33),
 'claim call': np.int64(16),
 'call claim': np.int64(3),
 'free call': np.int64(32),
 'chanc win': np.int64(15),
 'txt word': np.int64(88),
 'let know': np.int64(54),
 'go home': np.int64(37),
 'pleas call': np.int64(67),
 'lt gt': np.int64(58),
 'want go': np.int64(97),
 'first time': np.int64(31),
 'like lt': np.int64(55),
 'sorri call': np.int64(80),
 'call later': np.int64(8),
 'ur award': np.int64(90),
 'call custom': np.int64(4),
 'custom servic': np.int64(23),
 'cash prize': np.int64(14),
 'po box': np.int64(68),
 'tri contact': np.int64(85),
 'draw show': np.int64(28),
 'show prize': np.int64(79),
 'prize guarante': np.int64(73),
 'guarante call': np.int64(44),
 'valid hr': np.int64(95),
 'select receiv': np.int64(76),
 'privat account': np.int64(71),
 'account statement': np.int64(0),
 'statement show': np.int64(81),
 'call identifi': np.int64(5),
 'identifi code': np.int64(50),
 'code expir': np.int64(20),
 'urgent mobil': np.int64(94),
 'call lan

In [128]:
## trigram
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100, binary=True, ngram_range=(3,3))
X = cv.fit_transform(corpus).toarray()
X.shape

(5572, 100)

In [129]:
cv.vocabulary_

{'like lt gt': np.int64(43),
 'sorri call later': np.int64(79),
 'pleas call custom': np.int64(65),
 'call custom servic': np.int64(6),
 'custom servic repres': np.int64(22),
 'guarante cash prize': np.int64(35),
 'draw show prize': np.int64(23),
 'show prize guarante': np.int64(77),
 'prize guarante call': np.int64(70),
 'valid hr ppm': np.int64(96),
 'special select receiv': np.int64(81),
 'speak live oper': np.int64(80),
 'live oper claim': np.int64(45),
 'privat account statement': np.int64(68),
 'account statement show': np.int64(0),
 'call identifi code': np.int64(7),
 'identifi code expir': np.int64(40),
 'bonu caller prize': np.int64(4),
 'select receiv award': np.int64(76),
 'match pleas call': np.int64(54),
 'urgent tri contact': np.int64(95),
 'lt decim gt': np.int64(47),
 'secret admir look': np.int64(75),
 'admir look make': np.int64(1),
 'look make contact': np.int64(46),
 'make contact find': np.int64(53),
 'contact find reveal': np.int64(19),
 'find reveal think': np.in

In [130]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

### Data Preprocseeing step using TF and IDF

In [131]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
lemmatizer_word = WordNetLemmatizer()

In [132]:
corpus = []
for i in range(0, len(matter)):
  review=re.sub('[^a-zA-Z]',' ', matter['text'][i])
  review=review.lower()
  review=review.split()
  review=[lemmatizer_word.lemmatize(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

In [133]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

### Term Frequency (TF) and Inverse Dicument Frequency (IDF)

In [134]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=100)
X = tfidf.fit_transform(corpus).toarray()

In [135]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.434, 0, 0, 0.461, 0.544, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.55, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.456, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0.473, 0, 0, 0, 0, 0, 0, 0, 0.492, 0, 0, 0, 0, 0, 0, 0, 0.571, 0, 0, 0, 0, 0, 0],
       [0.465, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.486, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.574, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

### Applying N-gram technique

In [136]:
tfidf = TfidfVectorizer(max_features=100, ngram_range=(2,2))
X = tfidf.fit_transform(corpus).toarray()

In [137]:
tfidf.vocabulary_

{'free entry': np.int64(33),
 'claim call': np.int64(16),
 'call claim': np.int64(3),
 'claim code': np.int64(17),
 'free call': np.int64(32),
 'chance win': np.int64(15),
 'txt word': np.int64(89),
 'let know': np.int64(54),
 'please call': np.int64(68),
 'lt gt': np.int64(58),
 'want go': np.int64(97),
 'first time': np.int64(31),
 'like lt': np.int64(55),
 'sorry call': np.int64(80),
 'call later': np.int64(8),
 'ur awarded': np.int64(90),
 'hi hi': np.int64(47),
 'call customer': np.int64(4),
 'customer service': np.int64(24),
 'guaranteed cash': np.int64(43),
 'cash prize': np.int64(14),
 'po box': np.int64(70),
 'trying contact': np.int64(86),
 'draw show': np.int64(29),
 'show prize': np.int64(79),
 'prize guaranteed': np.int64(74),
 'guaranteed call': np.int64(42),
 'valid hr': np.int64(95),
 'selected receive': np.int64(76),
 'private account': np.int64(72),
 'account statement': np.int64(0),
 'statement show': np.int64(82),
 'call identifier': np.int64(5),
 'identifier code':

### Word2Vec

In [138]:
!pip install gensim

In [139]:
from gensim.models import Word2Vec, KeyedVectors

### Using a word2vec model, trained and developed by stanford NLP Group

In [140]:
import gensim.downloader as api
w2v = api.load("glove-wiki-gigaword-100")
king_vec = w2v["king"]

In [141]:
king_vec.shape

(100,)

In [142]:
w2v["football"]

array([0.439, 0.105, 0.46, -1.07, -1.25, 0.764, 0.475, 0.0839, -0.913, -0.273, -0.0186, -1.18, 0.227, 0.168, -0.522, 0.113, 1.38, 0.119, -0.377, 0.511, -0.883, 0.963, 0.181, -0.407, 0.0362, -0.744, -0.00274, -0.701, 0.531, 0.451, -0.729, 1.06, -0.28, -0.638, 0.156, -0.469, -1.01, 1.03, -1.44, -0.275, 0.049, 0.14, 0.431, -0.788, 0.411, 0.585, 1.02, -0.184, 0.275, -0.909, -0.304, -0.174, 0.0209, 0.628, 0.11, -2.39, -0.564, -0.272, 0.987, 0.706, -0.512, 0.526, -0.785, -0.687, 0.381, 0.0976, -0.202, 0.432, -0.305, 0.579, 0.626, -0.474, 0.338, -0.284, -0.0975, 0.196, 0.548, 0.599, -0.416, 0.102, 0.677, 0.0042, -0.124, -0.766, -0.274, -0.682, -1.08, -0.167, 0.817, 0.027, -0.387, 0.404, -1.1, 0.647, -0.128, -0.261, -0.967, 0.881, 1.01, -0.0222], dtype=float32)

In [143]:
w2v.most_similar("stress")

[('pain', 0.725872278213501),
 ('anxiety', 0.7095138430595398),
 ('fatigue', 0.7049359679222107),
 ('mental', 0.701725423336029),
 ('psychological', 0.6904554963111877),
 ('physical', 0.6795199513435364),
 ('severe', 0.6727946400642395),
 ('problems', 0.6613970994949341),
 ('risk', 0.6541153788566589),
 ('muscle', 0.645975649356842)]

In [144]:
w2v.similarity("anxiety", "stress")

np.float32(0.70951384)

In [145]:
matter

,label,text
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


### 1. Data Preprocessing

In [146]:
# Importing nltk, re, stopwords and wordnet (for lemmatization)
import pandas as pd
import numpy as np
import nltk
import re
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [147]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
port_stemmer = PorterStemmer()

In [148]:
corpus = []
for i in range(0, len(matter)):
  review = re.sub('[^a-zA-Z]', ' ', matter['text'][i])
  review=review.lower()
  review = review.split()
  review=[port_stemmer.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

In [149]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [150]:
y = pd.get_dummies(matter['label'])
y = y.iloc[:,0].values

###2. splitting data to train and test

In [151]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size=0.2)

In [152]:
len(X_train), len(y_train)

(4457, 4457)

### 3. Bag of Words

In [153]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500, ngram_range=(1,2))

In [154]:
# Input Features
X_train = cv.fit_transform(X_train).toarray()
X_test = cv.transform(X_test).toarray()

In [155]:
np.set_printoptions(edgeitems=30, linewidth=10000,
                    formatter=dict(float=lambda x: "%.3g" % x))
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [156]:
cv.vocabulary_

{'sir': np.int64(1892),
 'need': np.int64(1408),
 'bank': np.int64(146),
 'account': np.int64(12),
 'address': np.int64(21),
 'yo': np.int64(2491),
 'gonna': np.int64(825),
 'still': np.int64(1986),
 'stock': np.int64(1988),
 'tomorrow': np.int64(2147),
 'today': np.int64(2137),
 'tri': np.int64(2175),
 'get': np.int64(775),
 'tri get': np.int64(2178),
 'sure': np.int64(2034),
 'make': np.int64(1249),
 'smoke': np.int64(1916),
 'want': np.int64(2333),
 'told': np.int64(2145),
 'much': np.int64(1383),
 'tri make': np.int64(2179),
 'smoke much': np.int64(1917),
 'got': np.int64(847),
 'lesson': np.int64(1140),
 'sch': np.int64(1791),
 'doc': np.int64(540),
 'wait': np.int64(2319),
 'room': np.int64(1755),
 'depend': np.int64(514),
 'would': np.int64(2442),
 'like': np.int64(1153),
 'treat': np.int64(2174),
 'would like': np.int64(2443),
 'wat': np.int64(2345),
 'dear': np.int64(493),
 'sleep': np.int64(1902),
 'ah': np.int64(37),
 'help': np.int64(927),
 'pick': np.int64(1559),
 'wherev'

In [157]:
from sklearn.naive_bayes import MultinomialNB
spam_detection_model = MultinomialNB().fit(X_train, y_train)

In [158]:
y_pred = spam_detection_model.predict(X_test)

In [159]:
y_pred

array([False,  True,  True,  True,  True, False,  True,  True, False,  True,  True,  True,  True, False,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False, ...,  True,  True,  True,  True,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False, False,  True])

In [160]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9766816143497757

### TF-IDF

In [161]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size=0.2)

In [162]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=2500, ngram_range=(1,2))
X_train = tfidf.fit_transform(X_train).toarray()
X_test = tfidf.transform(X_test).toarray()

In [163]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [164]:
tfidf.vocabulary_

{'nd': np.int64(1400),
 'time': np.int64(2122),
 'tri': np.int64(2175),
 'contact': np.int64(402),
 'pound': np.int64(1627),
 'prize': np.int64(1653),
 'claim': np.int64(333),
 'easi': np.int64(574),
 'call': np.int64(236),
 'per': np.int64(1552),
 'min': np.int64(1297),
 'bt': np.int64(213),
 'nation': np.int64(1396),
 'rate': np.int64(1684),
 'nd time': np.int64(1402),
 'time tri': np.int64(2129),
 'tri contact': np.int64(2176),
 'contact pound': np.int64(408),
 'pound prize': np.int64(1629),
 'prize claim': np.int64(1655),
 'claim easi': np.int64(336),
 'easi call': np.int64(575),
 'call per': np.int64(253),
 'per min': np.int64(1554),
 'bt nation': np.int64(215),
 'nation rate': np.int64(1397),
 'got': np.int64(833),
 'ur': np.int64(2234),
 'mail': np.int64(1239),
 'thank': np.int64(2091),
 'look': np.int64(1186),
 'forward': np.int64(709),
 'lot': np.int64(1198),
 'support': np.int64(2033),
 'less': np.int64(1137),
 'rememb': np.int64(1721),
 'one': np.int64(1495),
 'tomorrow': np

In [165]:
from sklearn.naive_bayes import MultinomialNB
spam_detection_tfidf = MultinomialNB().fit(X_train, y_train)

In [166]:
y_pred = spam_detection_tfidf.predict(X_test)
y_pred

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, ...,  True,  True,  True, False,  True,  True,  True, False,  True,  True, False,  True,  True,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True, False,  True,  True,  True,  True])

In [167]:
accuracy_tfidf = accuracy_score(y_test, y_pred)
accuracy

0.9766816143497757

### Word2Vec

In [192]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [193]:
corpus = []
for i in range(0, len(matter)):
  review = re.sub('[^a-zA-Z]', ' ', matter['text'][i])
  review=review.lower()
  review = review.split()
  review=[lemmatizer.lemmatize(word) for word in review]
  review=' '.join(review)
  corpus.append(review)

In [194]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

In [195]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [196]:
words=[]
for sent in corpus:
  sent_token = sent_tokenize(sent)
  for sent in sent_token:
    words.append(simple_preprocess(sent))

In [197]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

In [198]:
import gensim
model = gensim.models.Word2Vec(words)

In [212]:
matter.shape

(5572, 2)

In [214]:
X_arr.shape

(5569, 100)

In [199]:
## Getting all the vocabulary
model.wv.index_to_key

['to',
 'you',
 'the',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'if',
 'will',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'day',
 'ok',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'good',
 'time',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'love',
 'text',
 'only',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'don',
 'stop',
 'she',
 'home',
 'about',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'our',
 'think',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'they',
 'later',
 'please',
 'any',
 'pls',
 'her',
 'ha',
 'did',
 'co',
 'msg',
 'been',
 'min',
 'an',
 'some',
 'dear',
 'night',
 'make',
 'who',
 'here',
 'message',
 'well',
 'say',
 'where',
 're',
 'thing',
 'much',
 'hope

In [200]:
model.corpus_count

5569

In [201]:
model.wv['happy']

array([-0.306, 0.39, 0.11, 0.13, 0.158, -0.779, 0.187, 0.73, -0.431, -0.125, -0.25, -0.627, 0.0109, 0.123, 0.358, -0.22, 0.191, -0.409, -0.0925, -0.907, 0.324, 0.306, 0.134, -0.313, -0.13, 0.0639, -0.535, -0.343, -0.361, 0.0616, 0.415, 0.00773, 0.139, -0.342, -0.19, 0.619, -0.00218, -0.192, -0.181, -0.54, 0.254, -0.404, -0.253, 0.0566, 0.384, -0.0147, -0.315, -0.0831, 0.168, 0.204, 0.25, -0.296, -0.0612, 0.104, -0.104, 0.27, 0.244, 0.11, -0.44, 0.206, -0.00829, 0.19, -0.0993, -0.222, -0.515, 0.379, 0.135, 0.282, -0.544, 0.493, -0.318, 0.138, 0.486, -0.25, 0.418, 0.219, 0.0394, -0.196, -0.27, 0.0455, -0.176, -0.00277, -0.302, 0.549, -0.174, 0.0612, 0.0676, 0.315, 0.633, -0.0351, 0.475, 0.218, 0.0455, 0.215, 0.522, 0.504, 0.162, -0.305, 0.234, -0.145], dtype=float32)

In [202]:
model.wv['happy'].shape

(100,)

In [203]:
words[1]

['ok', 'lar', 'joking', 'wif', 'oni']

In [204]:
def avg_word2vec(doc):
  vectors = [model.wv[word] for word in doc if word in model.wv]

  if len(vectors) == 0:
    return np.zeros(model.vector_size)

  return np.mean(vectors, axis=0)

In [181]:
!pip install tqdm

In [205]:
from tqdm import tqdm
X = [avg_word2vec(doc) for doc in words]

In [206]:
X

[array([-0.185, 0.266, 0.0677, 0.0994, 0.0757, -0.531, 0.137, 0.484, -0.3, -0.0954, -0.17, -0.419, -0.00805, 0.0759, 0.229, -0.144, 0.115, -0.271, -0.0436, -0.591, 0.198, 0.197, 0.0849, -0.194, -0.0864, 0.0365, -0.391, -0.23, -0.246, 0.0339, 0.287, -0.00266, 0.1, -0.244, -0.12, 0.413, 0.00404, -0.142, -0.129, -0.365, 0.151, -0.275, -0.174, 0.0274, 0.258, -0.00861, -0.212, -0.0581, 0.127, 0.141, 0.168, -0.21, -0.0475, 0.0781, -0.0988, 0.183, 0.172, 0.0707, -0.3, 0.149, -0.00184, 0.129, -0.0635, -0.138, -0.338, 0.259, 0.0819, 0.183, -0.36, 0.321, -0.219, 0.124, 0.319, -0.18, 0.302, 0.158, 0.0106, -0.125, -0.183, 0.0361, -0.122, -0.0204, -0.221, 0.381, -0.138, 0.0268, 0.056, 0.214, 0.397, -0.0269, 0.288, 0.14, 0.0308, 0.143, 0.358, 0.312, 0.0882, -0.194, 0.153, -0.102], dtype=float32),
 array([-0.161, 0.235, 0.0576, 0.0939, 0.0633, -0.483, 0.114, 0.435, -0.258, -0.0699, -0.151, -0.368, -0.0118, 0.0591, 0.205, -0.137, 0.108, -0.246, -0.036, -0.521, 0.179, 0.17, 0.0702, -0.175, -0.078, 0.02

In [207]:
len(X)

5569

In [209]:
X_arr = np.array(X)
X_arr

array([[-0.185, 0.266, 0.0677, 0.0994, 0.0757, -0.531, 0.137, 0.484, -0.3, -0.0954, -0.17, -0.419, -0.00805, 0.0759, 0.229, -0.144, 0.115, -0.271, -0.0436, -0.591, 0.198, 0.197, 0.0849, -0.194, -0.0864, 0.0365, -0.391, -0.23, -0.246, 0.0339, ..., -0.219, 0.124, 0.319, -0.18, 0.302, 0.158, 0.0106, -0.125, -0.183, 0.0361, -0.122, -0.0204, -0.221, 0.381, -0.138, 0.0268, 0.056, 0.214, 0.397, -0.0269, 0.288, 0.14, 0.0308, 0.143, 0.358, 0.312, 0.0882, -0.194, 0.153, -0.102],
       [-0.161, 0.235, 0.0576, 0.0939, 0.0633, -0.483, 0.114, 0.435, -0.258, -0.0699, -0.151, -0.368, -0.0118, 0.0591, 0.205, -0.137, 0.108, -0.246, -0.036, -0.521, 0.179, 0.17, 0.0702, -0.175, -0.078, 0.0282, -0.349, -0.212, -0.217, 0.0278, ..., -0.193, 0.11, 0.284, -0.164, 0.271, 0.134, 0.00149, -0.11, -0.162, 0.0216, -0.102, -0.0153, -0.197, 0.338, -0.128, 0.0257, 0.0534, 0.191, 0.346, -0.0275, 0.255, 0.12, 0.0233, 0.124, 0.313, 0.268, 0.0737, -0.179, 0.13, -0.0889],
       [-0.181, 0.281, 0.0902, 0.128, 0.0762, -0.58

In [210]:
X_arr.shape

(5569, 100)

In [211]:
X[0].shape

(100,)

In [216]:
y = matter[list(map(lambda x: len(x)>0, corpus))]
y = pd.get_dummies(y['label'])
y = y.iloc[:,0].values

In [217]:
y.shape

(5569,)

In [218]:
X[0]

array([-0.185, 0.266, 0.0677, 0.0994, 0.0757, -0.531, 0.137, 0.484, -0.3, -0.0954, -0.17, -0.419, -0.00805, 0.0759, 0.229, -0.144, 0.115, -0.271, -0.0436, -0.591, 0.198, 0.197, 0.0849, -0.194, -0.0864, 0.0365, -0.391, -0.23, -0.246, 0.0339, 0.287, -0.00266, 0.1, -0.244, -0.12, 0.413, 0.00404, -0.142, -0.129, -0.365, 0.151, -0.275, -0.174, 0.0274, 0.258, -0.00861, -0.212, -0.0581, 0.127, 0.141, 0.168, -0.21, -0.0475, 0.0781, -0.0988, 0.183, 0.172, 0.0707, -0.3, 0.149, -0.00184, 0.129, -0.0635, -0.138, -0.338, 0.259, 0.0819, 0.183, -0.36, 0.321, -0.219, 0.124, 0.319, -0.18, 0.302, 0.158, 0.0106, -0.125, -0.183, 0.0361, -0.122, -0.0204, -0.221, 0.381, -0.138, 0.0268, 0.056, 0.214, 0.397, -0.0269, 0.288, 0.14, 0.0308, 0.143, 0.358, 0.312, 0.0882, -0.194, 0.153, -0.102], dtype=float32)

In [222]:
df = pd.DataFrame(X)

In [223]:
df.shape

(5569, 100)

In [225]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.184592,0.265945,0.067658,0.099388,0.075691,-0.531253,0.136795,0.483797,-0.299923,-0.095368,...,0.287663,0.140246,0.030812,0.142732,0.357706,0.312252,0.088198,-0.193591,0.152749,-0.102324
1,-0.161360,0.234984,0.057587,0.093913,0.063258,-0.482799,0.114406,0.435250,-0.257844,-0.069931,...,0.255425,0.119715,0.023342,0.124144,0.313195,0.267893,0.073706,-0.179372,0.130412,-0.088881
2,-0.181119,0.281408,0.090242,0.127531,0.076176,-0.585798,0.135911,0.488971,-0.318031,-0.112826,...,0.280263,0.150754,0.017420,0.147466,0.383674,0.301762,0.065212,-0.224510,0.186908,-0.113004
3,-0.252428,0.364981,0.085585,0.138998,0.099106,-0.720768,0.184494,0.664247,-0.410895,-0.117526,...,0.391259,0.183076,0.035202,0.196476,0.471848,0.424937,0.117290,-0.270976,0.199428,-0.127742
4,-0.220765,0.302509,0.079345,0.111074,0.097712,-0.603831,0.148891,0.562803,-0.344567,-0.109872,...,0.338882,0.147254,0.031981,0.163556,0.393145,0.361122,0.095524,-0.236307,0.167321,-0.117503


In [226]:
X=df ## independent features

In [234]:
df['Output'] = y

In [235]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,Output
0,-0.184592,0.265945,0.067658,0.099388,0.075691,-0.531253,0.136795,0.483797,-0.299923,-0.095368,...,0.140246,0.030812,0.142732,0.357706,0.312252,0.088198,-0.193591,0.152749,-0.102324,True
1,-0.161360,0.234984,0.057587,0.093913,0.063258,-0.482799,0.114406,0.435250,-0.257844,-0.069931,...,0.119715,0.023342,0.124144,0.313195,0.267893,0.073706,-0.179372,0.130412,-0.088881,True
2,-0.181119,0.281408,0.090242,0.127531,0.076176,-0.585798,0.135911,0.488971,-0.318031,-0.112826,...,0.150754,0.017420,0.147466,0.383674,0.301762,0.065212,-0.224510,0.186908,-0.113004,False
3,-0.252428,0.364981,0.085585,0.138998,0.099106,-0.720768,0.184494,0.664247,-0.410895,-0.117526,...,0.183076,0.035202,0.196476,0.471848,0.424937,0.117290,-0.270976,0.199428,-0.127742,True
4,-0.220765,0.302509,0.079345,0.111074,0.097712,-0.603831,0.148891,0.562803,-0.344567,-0.109872,...,0.147254,0.031981,0.163556,0.393145,0.361122,0.095524,-0.236307,0.167321,-0.117503,True


In [227]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [229]:
X_train.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
333,-0.157210,0.285379,0.089825,0.129050,0.069406,-0.576998,0.140883,0.474550,-0.306439,-0.114140,...,0.269325,0.149882,0.013344,0.133331,0.395747,0.279443,0.064088,-0.205870,0.184504,-0.115701
3184,-0.236862,0.326129,0.073698,0.115385,0.099575,-0.624442,0.156589,0.590492,-0.363903,-0.112604,...,0.355103,0.157125,0.037146,0.171202,0.416547,0.385458,0.107550,-0.231679,0.182435,-0.119187
4036,-0.211485,0.300807,0.075766,0.100920,0.089989,-0.591391,0.144760,0.546673,-0.333269,-0.107960,...,0.329360,0.153912,0.035203,0.154087,0.395036,0.349462,0.099839,-0.218537,0.173565,-0.114865
329,-0.262128,0.342412,0.096526,0.121313,0.124068,-0.696645,0.158042,0.641784,-0.387894,-0.143362,...,0.404158,0.157145,0.028334,0.165368,0.432632,0.407618,0.091742,-0.293875,0.195899,-0.125421
3561,-0.250283,0.324207,0.080380,0.108179,0.112169,-0.635606,0.156755,0.603165,-0.363277,-0.127821,...,0.373097,0.153937,0.038014,0.162670,0.408557,0.386128,0.102865,-0.252776,0.177180,-0.110807


In [231]:
y_train

array([False,  True,  True,  True,  True,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True, False, False,  True, False,  True,  True,  True,  True,  True,  True, ...,  True,  True,  True,  True, False, False,  True, False,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True, False,  True])

In [232]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()

In [233]:
classifier.fit(X_train, y_train)

RandomForestClassifier()

In [236]:
y_pred = classifier.predict(X_test)

In [237]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)

In [238]:
accuracy

0.9649910233393177